version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: some-postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: myuser
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Mount the initialization scripts

  # rust_api:
  #   build: .
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - postgres


volumes:
  postgres_data: